# Generated by Django 4.0.2 on 2022-02-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_isdelivered_alter_order_deliveredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/tesrab_bunny.png', null=True, upload_to=''),
        ),
    ]
